[[observations]]
name = "machine_heating_consumption"
ext_id = "glt_hnht_only.HNHT.CentralMachineHeatingSystem.WMZ300.sensorState.fHeatFlowRate"
is_ext_output = true
low_value=-10
high_value=200

[[observations]]
name = "pwt_system_state"
ext_id = "glt_hnht_only.HNHT_HNLT.HeatExchanger1System.systemState.nOperatingState"
is_ext_output = true
low_value=0
high_value=4

[[observations]]
name = "lastverlauf"
scenario_id = "lastverlauf"
from_scenario = true

[[actions]]
name = "HNHT_HNLT.HeatExchanger1System.RV315.setSetPoint.fSetPointAlgorithm"
ext_id = "glt_hnht_only.HNHT_HNLT.HeatExchanger1System.RV315.setSetPoint.fSetPointAlgorithm"
is_ext_input = true
low_value=-10
high_value=200
